server:
  port: 8070

spring:
  application:
    name: CampApp
  rabbitmq:
    username: esvqbdto
    password: zBM3bq0R1B6nB5ON2KwpTPIfTaKw71e3
    host: rat.rmq2.cloudamqp.com
    port: 5671
    virtual-host: esvqbdto
    ssl:
      enabled: true

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CampApp?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



